### ISSUE TITLE
Add Preview Content to all Form Blocks

### ISSUE THREAD

**Issue by munirkamal** [nikolaystrikhar/gutenberg-forms#143]
We need to define preview content so that it is reviewable in the inserter and also makes the style picker nice.

https://developer.wordpress.org/block-editor/developers/block-api/block-registration/#example-optional

Nice article with examples.
https://mediaron.com/how-to-enable-gutenberg-block-previews/

P.S. This will also fix #138

**Comment by cristianraiber** [comment]
I think this is already implemented. @andyluak - can you please confirm?
