### ISSUE TITLE
Entries

### ISSUE THREAD

**Issue by Torbanio** [nikolaystrikhar/gutenberg-forms#153]
1. Entry Details: Fieldname instead of FieldID should be shown

2. Nice to have:
a. Entry Fields should be editable
b. Entry Overview: A additional Column "Checked" or "Done" with Checkbox would be nice.
c. Import/Export (already mentioned on github)

**Comment by munirkamal** [comment]
Yeah, I need to improve the entries screen with suggestions coming in. Adding this to ToDo.

**Comment by ZafarKamal123** [comment]
Hey @Torbanio,

Follow up:

- Improved Entries System has been added
- Read / Unread Status has been added in the entries
- Import / Export will be considered in a future update.

What would be the use case for editable entries?

**Comment by cristianraiber** [comment]
@andyluak - Editable entries or the possibility of adding notes would be useful for people doing sales or following up with leads as part of a team of people, where anyone can go in, read an entry, edit or leave a note for the next person.
