### ISSUE TITLE
register_rest_route warning for namespace name.

### ISSUE THREAD

**Issue by dovy** [nikolaystrikhar/gutenberg-forms#164]
```
register_rest_route was called incorrectly. Namespace must not start or end with a slash. Please see Debugging in WordPress for more information. (This message was added in version 5.4.2.)

register_rest_route()
wp-content/plugins/forms-gutenberg/controllers/entries/entries.controller.php:60
cwp_gf_Entries_Controller->register_routes()
wp-content/plugins/forms-gutenberg/controllers/index.php:13
```

;)

**Comment by ZafarKamal123** [comment]
Hey @dovy,
Thanks for mentioning this, I will definitely take another look at it! 👍

**Comment by dovy** [comment]
Super easy to fix, see: https://github.com/reduxframework/redux-framework-4/blob/master/redux-core/inc/classes/class-redux-rest-api-builder.php#L59

**Comment by ZafarKamal123** [comment]
Thanks, I will take a look at this and get back to you! 🤞

**Comment by haynzz** [comment]
I'm also having this issue also. 
On my local development machine I can't use the plugin.
Is there a workaround or any way to circumvent the exception? For me this is kind of a blocker.

I'm also willing to work on a pull request. Just not sure what makes sense?!
