### ISSUE TITLE
Send data to success URL

### ISSUE THREAD

**Issue by raphaguasta** [nikolaystrikhar/gutenberg-forms#165]
Hello guys!

I need to pass the collected data in form to the success URL.
It can be using query string(GET), POST into the success URL, cookies...

It's possible to do this today?

Thanks! :)

**Comment by cristianraiber** [comment]
@raphaguasta - not currently possible. Low on our priority list as well.

**Comment by nikolaystrikhar** [comment]
Issues already exists, called webhooks
