### ISSUE TITLE
Conditional logic based on select field option does not work

### ISSUE THREAD

**Issue by pshemek** [nikolaystrikhar/gutenberg-forms#166]
**Prerequisites:**

- WordPress 5.5
- TwentyTwenty
- Gutenberg Forms 1.9.0
- Safari MacOS

**Steps to reproduce problem:**

1. Add Form -> Standard
2. Insert a select field after existing name field (i.e. "Contact by" with options "e-mail", "phone")
3. Insert a text field (i.e "Phone number") and use condition: Show if -> Contact by -> Is Equal To -> phone
4. Save the form and go to the front-end
5. Select option "phone" in "Contact by" field
6. No additional field (phone) appears.

**Expected result:**

Phone field should appear when "Contact by" is set to "phone".

**Comment by nikolaystrikhar** [comment]
Tested, works.
