### ISSUE TITLE
Problems with browsing entries on multisite

### ISSUE THREAD

**Issue by pshemek** [nikolaystrikhar/gutenberg-forms#167]
Hello, is GF compatible with WPMU?

I cannot display entries submitted through the form and the console throws error 404 on REST API queries like:
`http://dev.local/index.php?rest_route=/wp/v2/cwp_gf_entries?page=1&per_page=10`

**Comment by ZafarKamal123** [comment]
Hey @macemmek,

Thanks for reporting this issue. We will definitely look into this. 👍

**Comment by ZafarKamal123** [comment]
Hey @macemmek,

I've tested this on WordPress Multisite and cannot replicate the error. Can you provide more information regarding this?

Thanks
- Zafar

**Comment by macemmek** [comment]
Well, I try.

Stats are showing a proper number of entries.

However viewing:
`/wp-admin/edit.php?post_type=cwp_gf_entries`
causes permissions error:

> Sorry, you are not allowed to edit posts in this post type.

I am logged-in super admin and things are happening on the root site of multisite.

![Zrzut ekranu 2020-08-28 o 19 53 25](https://user-images.githubusercontent.com/513306/91600415-34cde200-e968-11ea-8661-c01c674f287c.png)

**Comment by macemmek** [comment]
Now I see it.

Permalinks structure. The REST API error occurs when I switch to non-pretty permalinks (with GET variables).

However that permission error persists on /wp-admin/edit.php?post_type=cwp_gf_entries

**Comment by munirkamal** [comment]
Hi @macemmek 

Thank you to report that. I can confirm this is a bug not only with multisite but in general. It doesn't work when you have the permalink set to "plain".

Will fix it asap.

Regards,
Munir

**Comment by nikolaystrikhar** [comment]
Fixed. Will be rolled out in the next release.
