### ISSUE TITLE
PHP warnings with 2.0

### ISSUE THREAD

**Issue by darbymanning** [nikolaystrikhar/gutenberg-forms#168]
This is using WP 5.5.1.

Looks like there's an issue with the new version of Gutenberg Forms, I'm seeing the following php warnings:

```
Warning: include_once(/Users/darbymanning/Sites/ph/backend/web/app/plugins/forms-gutenberg/dashboard/wp-load.php): failed to open stream: No such file or directory in /Users/darbymanning/Sites/ph/backend/web/app/plugins/forms-gutenberg/dashboard/dashboard.php on line 6

Warning: include_once(): Failed opening '/Users/darbymanning/Sites/ph/backend/web/app/plugins/forms-gutenberg/dashboard/wp-load.php' for inclusion (include_path='.:/Applications/MAMP/bin/php/php7.3.9/lib/php') in /Users/darbymanning/Sites/ph/backend/web/app/plugins/forms-gutenberg/dashboard/dashboard.php on line 6
```

This is probably because I am using [bedrock](https://roots.io/docs/bedrock/master/installation/) so it isn't able to resolve the path correctly. From what I've read it's not recommended for plugins to load core files actually, so perhaps there could be another way to get this data?

**Comment by bakoe** [comment]
I’m having the same issue – any updates on this? 

@darbymanning Did you find a workaround around this problem?

**Comment by nikolaystrikhar** [comment]
Still an issue.
