### ISSUE TITLE
Google Recaptcha console error

### ISSUE THREAD

**Issue by janwidmer** [nikolaystrikhar/gutenberg-forms#170]
Hi There,

Thanks for the cool plugin. I am using it with Wordpress 5.5. When adding a form using the ReCaptcha, I get the following console error:

![image](https://user-images.githubusercontent.com/3381820/92229158-54ee2b80-eea9-11ea-8134-7008e9d39e0b.png)

I assume, that it happens, because the ReCaptcha library seem's to get loaded twice in the markup:

![Pasted_Image_04_09_20__12_23](https://user-images.githubusercontent.com/3381820/92229433-c4fcb180-eea9-11ea-97c0-cd86da85e6fe.jpg)

It would be nice, if the ReCaptcha library would just be loaded once.

**Comment by ZafarKamal123** [comment]
Hey @janwidmer,
 
Thanks for reporting this issue. I will definitely look into it! 👍

**Comment by cristianraiber** [comment]
This should be fixed in 2.2.7. 

cc @andyluak - please close this if this was already fixed.
