### ISSUE TITLE
[Feature Request] Add option to define custom "action" attribute in form

### ISSUE THREAD

**Issue by chvillanuevap** [nikolaystrikhar/gutenberg-forms#179]
I would like to use your plugin to submit a form to a different service. To do that, I need to submit the form to a custom `action` attribute in my form. I would like to see an option to customize that!

Thanks for a great plugin!

**Comment by cristianraiber** [comment]
@chvillanuevap - That's a great idea!

**Comment by nikolaystrikhar** [comment]
Exists.
