### ISSUE TITLE
Live usage of Gutenberg Forms - Notification -

### ISSUE THREAD

**Issue by paaljoachim** [nikolaystrikhar/gutenberg-forms#181]
Here are a few things that was discovered when using the Gutenberg Forms for a web site.

From (field)
Not filled in as I would assume From is the person who submitted the form. But getting the CC e-mail notification I see it sender says wordpress@opsalgard.no.

TO / CC

TO: E-mail address to the person who owns the site.
CC: Two e-mail addresses listed here: Example. t@t.com, e@e.com

![Screen Shot 2021-02-18 at 21 13 10](https://user-images.githubusercontent.com/5323259/108415676-2208db80-722e-11eb-8474-f2c1f268afc3.png)

Based on having two e-mail addresses such as mentioned above t@t.com, -space- e@e.com did not go through. I then assume I have to remove the space so it becomes like so: t@t.com,e@e.com.

**Comment by andrewstaffell** [comment]
Having this issue too – can't find a way of getting the from header to show the sender's name / email. 

Tried putting {{email}} type fields in the From field but has no effect, just comes from `wordpress@server`

**Comment by cristianraiber** [comment]
Related to #211

What you're looking for here is the `reply-to` field.

**Comment by andrewstaffell** [comment]
Thanks. Is there documentation, or can you give instructions, for how to set the `reply-to` field using the values of name/email form fields? I'm looking at the source code `triggers/email.php` and can't see how I would do this. What am I missing?

**Comment by cristianraiber** [comment]
@andrewstaffell - You're not missing anything. Currently, that's not implemented, but will be available w/ version 2.2.8 :)

**Comment by andrewstaffell** [comment]
Brilliant! Thanks.
