### ISSUE TITLE
Cleaning up the entries page.

### ISSUE THREAD

**Issue by paaljoachim** [nikolaystrikhar/gutenberg-forms#182]
I see no bulk edit drop down here to where I can choose to delete all the test e-mail entries.

![Screen Shot 2021-02-18 at 21 23 13](https://user-images.githubusercontent.com/5323259/108416932-a4de6600-722f-11eb-9b49-88352023202f.png)

First column says Form. It uses the default Form label added automatically.

------------

I am not able to change the name directly on the page that has the form. --> I should be able to give the form a name here.
![Screen Shot 2021-02-18 at 21 37 15](https://user-images.githubusercontent.com/5323259/108418403-7f525c00-7231-11eb-8c77-db4ed0633c58.png)

-------------

Back to Entries screen

Hovering over a Form

![Screen Shot 2021-02-18 at 21 24 00](https://user-images.githubusercontent.com/5323259/108417124-de16d600-722f-11eb-9b50-a257143c2d20.png)

It says Preview Form and Edit Form. 

Example from the All Pages screen. Here hovering over Contact page.
![Screen Shot 2021-02-18 at 21 40 14](https://user-images.githubusercontent.com/5323259/108418769-f687f000-7231-11eb-9bf8-81b8b44bf45b.png)

It would be nice to hover over an entry and see View l Trash l edit form
Perhaps skip the view form. As one is here to see the entry or delete it.

**Comment by nikolaystrikhar** [comment]
I would recommend to abandon this custom interface and use the default WP way.
