### ISSUE TITLE
Field ID with accents on letters - no resulting entry

### ISSUE THREAD

**Issue by theophanemayaud** [nikolaystrikhar/gutenberg-forms#186]
Hi, it seems after some trial and error that I found a bug. I'm from france, and therefore regularly have accented letters in words. And it seems that when form field IDs contain accents, there is a bug where the form entry data isn't submitted to the database.
I do receive an email with the form data, but both on the entries screen directly in the database table, there seems to be no data entry.

## More details on what happens in the entries page of the plugin :
In such a situation, and entry is indeed recorded, but all the content, field values etc are gone. I just get an empty entry (see image)

![image](https://user-images.githubusercontent.com/25605953/109967532-d48e7300-7cf1-11eb-8a7a-b6720f6b1548.png)

## More details on what happens in the database : 
(If I understood correctly, the entries are supposed to be in the wordpress wp_postmeta table. But there, in case there are accented letters, some entries are missing : 
### A form submitted where I fixed all the accented letters in IDs of fields results in : 
![image](https://user-images.githubusercontent.com/25605953/109967778-220ae000-7cf2-11eb-83fb-0859fad591e0.png)
### But a form submitted with some IDs having accented letters gives : 
![image](https://user-images.githubusercontent.com/25605953/109967913-4ebef780-7cf2-11eb-9f51-1fc7127bf33d.png)

## More details on what is received by email
It seems as I said, that although the form submission data isn't saved/fully saved to the database, I do receive an email with the complete data. In my case, there were lots of fields, images, and all were included in the mail. 
In fact, this is how I noticed where the error might come from : One field was identified as "Date_de_début_du_projet", and when I went back to the form to edit this id to simply Date_de_debut_du_projet, then made a test entry, the data was this time saved to the database on top of sent by email.

**Comment by nikolaystrikhar** [comment]
Solved, not ideally (removing accents for now to save in the DB), but at least works great.

I need to refactor many things there to solve it the perfect way.

**Comment by theophanemayaud** [comment]
That’s great anyways ! Thanks a lot. Accents are not necessary in my mind it was just that I didn’t know better and broke the form by using them without knowing 😅

**Comment by nikolaystrikhar** [comment]
Sure, thank you so much for creating an issue!
