### ISSUE TITLE
Undefined array key "admin_id" in submissions/entries.php on line 11"

### ISSUE THREAD

**Issue by donbowman** [nikolaystrikhar/gutenberg-forms#198]
installed, form works in the sense that it sends an email, displays.
but, it gets a 500 back from the server, indicating

Undefined array key "admin_id" in submissions/entries.php on line 11", the function below has the code.

I don't see anywhere i would set anything that might affect this, can anyone suggest how to debug, what its expecting, and from where?

```
function get_value_and_name($field)
{

    $value = $field['field_value'];
    $adminId = $field['decoded_entry']['admin_id'];

    $result = array();

    $result['value'] = $value;
    $result['admin_id'] = $adminId;

    return $result;
}
```

**Comment by sshebear** [comment]
Was this ever resolved as I have the same problem?

**Comment by nikolaystrikhar** [comment]
Resolved, but not the ideal way, I will take a look at it during refactoring.
