### ISSUE TITLE
HTML client side form validation messages not appearing on mobile

### ISSUE THREAD

**Issue by mendezona** [nikolaystrikhar/gutenberg-forms#201]
When a required field is left blank/filled with invalidate characters and not displayed in the window when form is submitted, the form scrolls to the required field that requires attention however no validation message is displayed.

Steps to reproduce:
1. Create new form with some required input fields and set messages for 'Required Error' and 'Invalid Name Error'
2. Save new form and preview/view on mobile/responsive mode on any web browser
3. Input invalid characters or leave blank for a required input field
4. Scroll down so that the required input field is not viewable in the window
5. Click submit

- Actual behaviour: Window will scroll to input field requiring attention
- Expected behaviour: Window will scroll to input field requiring attention **and display relevant error message**

The error messages display correctly on larger view width, and seem to be obscured/missing on mobile view widths.

**Comment by nikolaystrikhar** [comment]
Tested, worked.
