### ISSUE TITLE
can't get email `From` header to be form submitter (for quick reply)

### ISSUE THREAD

**Issue by andrewstaffell** [nikolaystrikhar/gutenberg-forms#211]
At the moment the From header is `wordpress@server.co.uk` – I think I should be able to set it to the submitter's name and email but it's not working. 

This screenshot illustrates what I am trying to do:

<img width="274" alt="Screenshot 2022-02-03 at 14 47 24" src="https://user-images.githubusercontent.com/696154/152355155-8f19190d-d2b5-4d7d-9c3e-c51f54912940.png">

Why doesn't this work? Is it a bug or is there a different procedure?

**Comment by andrewstaffell** [comment]
Ah yes, `reply-to` would be fine! Thanks.

How do I set those to the submitter’s details?

**Comment by cristianraiber** [comment]
cc @andyluak
