### ISSUE TITLE
Adding forms from post/pages should allow you to pick from existing built forms

### ISSUE THREAD

**Issue by cristianraiber** [nikolaystrikhar/gutenberg-forms#213]
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/7841556/152646840-cd324275-96b4-458e-aebf-ae7ae5f91afd.png">

**Comment by cristianraiber** [comment]
I already have a form created w/ the ID `30550` but, as you can see in the above screenshot, when trying to add it to a new page I can not select a previously built form, I can only build a new one.

**Comment by nikolaystrikhar** [comment]
It’s called a reusable form, maybe it makes sense to add a button to generate it.
But I’m not sure that block works, something to test and play with.
