### ISSUE TITLE
Show hint doesn't really have a purpose here. 

### ISSUE THREAD

**Issue by cristianraiber** [nikolaystrikhar/gutenberg-forms#214]
<img width="292" alt="image" src="https://user-images.githubusercontent.com/7841556/152646895-4840d054-677a-4d82-8416-7f6d623e44e8.png">

**Comment by cristianraiber** [comment]
If I filled in the Hint Text then it means I want it shown. 


What we could add here is a "position" option - if we want the hint text to be shown ABOVE or BELOW the field

Instead of hint text change it to "field description". We also need to add field placeholders in here. 

Here's how a field placeholder looks like: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_placeholder

**Comment by nikolaystrikhar** [comment]
Placeholders are already available.
Show hint is pretty valid, but should be moved to the Field Settings panel.
Hint text must be removed and should be able to be edited inside a block like placeholders or field title.

**Comment by nikolaystrikhar** [comment]
> Show hint is pretty valid, but should be moved to the Field Settings panel. 

Moved.

Created separated issues for other things.
