### ISSUE TITLE
Feedback on testing the newest version

### ISSUE THREAD

**Issue by paaljoachim** [nikolaystrikhar/gutenberg-forms#230]
Hey 

The following is some brainstorming and a test of the newest version of Gutenberg Forms. I have not been following only lately and some things might be repeated from other issues.

Some initial thoughts...
Gutenberg Forms could/should be made on block components rather than the Block editor (Perhaps it is, and perhaps I am just mixing up terms). Btw I would suggest that you also take a closer look at the various issues here: 

Gutenberg Forms could/should also work in none Gutenberg environments.

On to testing.
Installed and activated.
I notice this description:
"The Next Generation WordPress Form Builder. Build forms directly within Gutenberg editor live. Add & arrange form fields like blocks."

Gutenberg Forms sidebar entry shows up just below Comments. It would be nice with an option in settings to adjust the placement in the left WP menu. 

### Initial Feel

Sidebar structure:
Gutenberg Forms
-Gutenberg Forms
-Forms
-Entries

Cleaning up to become:
Gutenberg Forms
-Forms
-Entries
-Settings

As one starts with the Forms, goes on to Entries and have Settings last.
Two Gutenberg Forms titles under each other seems just a little weird.

### Forms

Initially this screen feels very empty. I wonder if some templates could be seen or in some way add an easy way to start out with a template.

**Clicking Add Form.**

![Screenshot 2022-02-16 at 11 14 54](https://user-images.githubusercontent.com/5323259/154243634-9fec0803-566f-4636-98e3-cf1e20816def.jpg)

I see a Library button on the top line. A Gutenberg Forms placeholder. Some info in the sidebar when Gutenberg Forms is clicked.

**Clicking Library.** 
I suddenly see it is linked in with Extendify Library. Link to a Premium version button in the top.
In general the library feels messy as there are too many elements in one screen. Even a chat bubble is seen.
I feel like I left my own web site and entered another site.
I am backing quickly out of that.... Kinda felt like walking into a teenager room where I just backed out of it and closed the door again.

**Gutenberg Forms - placeholder.**

Standard - Multi Step OR Insert Form.

Clicking Standard automatically adds a new form. (I noticed no option to choose from a starter template.)
I selected the form and clicked the DEL key but nothing happened. I wanted to delete the form and go back to the placeholder.
I also clicked the contextual (3 dot) drop down menu to click Remove block but there was no option to do so.
Ok I am refreshing the page without saving to remove the form. That did not help. I removed each field and after deleting the last field the standard form returned.... Weird...
Ok I am leaving the forms page.  There is now a draft form in the Forms page.

Adding a new form.
Clicking the Insert Form (which is actually select/choose template)
I remember the last time I tested Gutenberg Forms that it had a "ton" of templates to choose from. Kinda overwhelming with all the choices. I selected Contact -> Contact Form and clicked the Insert Form button. No form was added to the page.

I made this gif:

![Clicking-Insert-Form](https://user-images.githubusercontent.com/5323259/154245944-4f174dc0-dade-4f00-9dfe-a5d842387eae.gif)

Backing out of the Forms page.
Entries page looks pretty nice.

Settings have a Messages area. That is helpful.
There is an Import. What about an Export?

I am stopping my testing.
There are a few things to address. I assume I can retest again in a few months time.

**Comment by nikolaystrikhar** [comment]
> Sidebar structure:

Will be updated in the next release.

**Comment by nikolaystrikhar** [comment]
Nothing serious except the copy of https://github.com/nikolaystrikhar/gutenberg-forms/issues/157 which will be fixed later
