### ISSUE TITLE
`.distignore` breaks the WP composer package (at wpackagist)

### ISSUE THREAD

**Issue by drzraf** [nikolaystrikhar/gutenberg-forms#237]
I use Bedrock for composer-based installations.
When installing from `wpackagist` (https://wpackagist.org/search?q=forms-gutenberg&type=any&search=), the resulting package is missing the `dist/*` folder (the Gutenberg block depends upon).
This is likely related to the `.distignore` file.

**Comment by nikolaystrikhar** [comment]
Fixed.
